local tablex = require 'ldk.tablex'

local function apple() return {name='apple',color='red',price=200} end
local function banana() return {name='banana',color='yello',price=50} end
local function orange() return {name='orange',color='orange',price=100} end
local function fixtures() return {apple(),banana(),orange()} end
local function fixtures2() return {x=1,y=2,z=3} end

describe("#tablex", function()
  it("should aggregate to a value", function()
    assert.equal(0, tablex.aggregate({}, 0, function(_, v, acc)
      return v + acc
    end))
    assert.equal(350, tablex.aggregate(fixtures(), 0, function(_, v, acc)
      return v.price + acc
    end))
  end)
  describe("all", function()
    it("should return true if the condition is true for all the key-value pairs of the table", function()
      assert.is_true(tablex.all(fixtures(), function() return true end))
      assert.is_true(tablex.all(fixtures(), function(_, v) return v.price > 0 end))
      assert.is_true(tablex.all(fixtures(), function(_, v) return v.price < 1000 end))
      assert.is_true(tablex.all(fixtures(), function(_, v) return v.name ~= 'pear' end))
    end)
    it("should return false if the condition is false for any of the  key-value pairs of the table", function()
      assert.is_false(tablex.all(fixtures(), function()return false end))
      assert.is_false(tablex.all(fixtures(), function(_, v) return v.price <= 0 end))
      assert.is_false(tablex.all(fixtures(), function(_, v) return v.price >= 1000 end))
      assert.is_false(tablex.all(fixtures(), function(_, v) return v.name ~= 'apple' end))
    end)
  end)
  describe("any", function()
    it("should return true if the condition is true for any the key-value pairs of the table", function()
      assert.is_true(tablex.any(fixtures(), function() return true end))
      assert.is_true(tablex.any(fixtures(), function(_, v) return v.price > 0 end))
      assert.is_true(tablex.any(fixtures(), function(_, v) return v.price < 1000 end))
      assert.is_true(tablex.any(fixtures(), function(_, v) return v.name ~= 'pear' end))
    end)
    it("should return false if the condition is false for all of the  key-value pairs of the table", function()
      assert.is_false(tablex.any(fixtures(), function()return false end))
      assert.is_false(tablex.any(fixtures(), function(_, v) return v.price <= 0 end))
      assert.is_false(tablex.any(fixtures(), function(_, v) return v.price >= 1000 end))
      assert.is_false(tablex.any(fixtures(), function(_, v) return v.name == 'pear' end))
    end)
  end)
  describe("sum", function()
    it("should return the sum of the elements of the table after the transform has been applied", function()
      assert.equal(0, tablex.sum({}))
      assert.equal(6, tablex.sum(fixtures2()))
      assert.equal(6, tablex.sum(fixtures2(), function(_, v) return v end))
    end)
    it("should report bad arguments", function()
      assert.error(function()
        tablex.sum({"not a number"})
      end)
    end)
  end)
  describe("group_by", function()
    it("should group elements by the given selector", function()
      assert.same({[1]={[1]=1,[2]=1},[3]={[3]=3,[4]=3},[5]={[5]=5,[6]=5}}, tablex.group_by({1,1,3,3,5,5}, function(_, v) return v end))
    end)
  end)
  describe("max", function()
    it("should return maximum element in the table", function()
      assert.is_nil(tablex.max({}))
      assert.same({3,3}, {tablex.max({1,2,3})})
    end)
    describe("max_by", function()
      it("should return maximum element in the table according to f", function()
        assert.is_nil(tablex.max_by({}, function(x)
          return x
        end))
        assert.same({1,apple()}, {tablex.max_by(fixtures(), function(x) return x.price end)})
      end)
    end)
    it("should report bad arguments", function()
      assert.error(function()
        tablex.max({{}, {}})
      end)
    end)
  end)
  describe("min", function()
    it("should return minimum element in the table", function()
      assert.is_nil(tablex.min({}))
      assert.same({1,1}, {tablex.min({1,2,3})})
    end)
    describe("min_by", function()
      it("should return minimum element in the table according to f", function()
        assert.is_nil(tablex.min_by({}, function(x)
          return x
        end))
        assert.same({2,banana()}, {tablex.min_by(fixtures(), function(x) return x.price end)})
      end)
    end)
    it("should report bad arguments", function()
      assert.error(function()
        tablex.min({{}, {}})
      end)
    end)
  end)
  describe("avg", function()
    it("should return the average of the elements of the table after the transform has been applied", function()
      assert.is_nil(tablex.avg({}))
      assert.equal(2, tablex.avg(fixtures2()))
      assert.equal(4, tablex.avg(fixtures2(), function(_, v) return 2 * v end))
    end)
    it("should report bad arguments", function()
      assert.error(function()
        tablex.avg({"not a number"})
      end)
    end)
  end)
  describe("fill", function()
    it("should fill the table with the right value", function()
      assert.same({1,1,1}, tablex.fill({1,2,3}, 1))
      assert.same({}, tablex.fill({1,2,3}))
    end)
  end)
  describe("eq", function()
    it("should return true when the tables are the same", function()
      assert.is_true(tablex.eq({}, {}))
      assert.is_true(tablex.eq(fixtures(), fixtures()))
    end)
    it("should return false when the tables are not the same", function()
      assert.is_false(tablex.eq({}, fixtures()))
      assert.is_false(tablex.eq(fixtures(), fixtures2()))
    end)
  end)
  describe("is_empty", function()
    it("should return true if the table is empty", function()
      assert.is_true(tablex.is_empty({}))
    end)
    it("should return false if the table is not empty", function()
      assert.is_false(tablex.is_empty(fixtures()))
    end)
  end)
  describe("count", function()
    it("should count all the key-value pairs satisfying the given condition", function()
      assert.equal(3, tablex.count(fixtures(), function() return true end))
      assert.equal(3, tablex.count(fixtures(), function(_, v) return v.price > 0 end))
      assert.equal(0, tablex.count(fixtures(), function(_, v) return v.price < 0 end))
      assert.equal(1, tablex.count(fixtures(), function(_, v) return v.name == 'apple' end))
    end)
  end)
  describe("find", function()
    it("should return the key-value pair satisying the given condition", function()
      local k, v = tablex.find(fixtures(), function(_, v)
        return v.name == 'apple'
      end)
      assert.is_false(k == nil)
      assert.is_false(v == nil)
    end)
  end)
  describe("contains_value", function()
    it("should return true if the value pair is in the table", function()
      assert.is_true(tablex.contains_value(fixtures(), 'apple', function(x, y)
        return x.name == y
      end))
    end)
    it("should return false if the value pair is in not the table", function()
      assert.is_false(tablex.contains_value(fixtures(), 'pear', function(x, y)
        return x.name == y
      end))
    end)
  end)
  describe("filter", function()
    it("should return all the key-value pairs satisfying the specified condition", function()
      assert.same({}, tablex.filter(fixtures(), function() return false end))
      assert.same(fixtures(), tablex.filter(fixtures(), function() return true end))
      assert.same({apple()}, tablex.filter(fixtures(), function(_, v)
        return v.name == 'apple'
      end))
    end)
  end)
  describe("map", function()
    it("should return the right values", function()
      assert.same({}, tablex.map({}, function() return true end))
      assert.same({a = 2}, tablex.map({a = 1}, function(k, v)
        return k, v * 2
      end))
    end)
  end)
  describe("remove_if", function()
    it("should remove a key-value pair satisfying the specified condition", function()
      assert.is_true(tablex.remove_if(fixtures(), function(_, v)
        return v.name == 'apple'
      end))
      assert.is_false(tablex.remove_if(fixtures(), function(_, v)
        return v.price > 1000
      end))
    end)
  end)
  describe("remove_all_if", function()
    it("should remove all the key-value pairs satisfying the specified condition", function()
      assert.equal(2, tablex.remove_all_if({a = 1, b = 2, c = 2, d = 4}, function(_, v)
        return v == 2
      end))
      assert.equal(0, tablex.remove_all_if({a = 1, b = 2, c = 2, d = 4}, function(_, v)
        return v == 5
      end))
    end)
  end)
  describe("copy", function()
    it("should copy all elements", function()
      assert.same(fixtures(), tablex.copy(fixtures(), {}))
    end)
  end)
  describe("keys", function()
    it("should return the keys of the table", function()
      assert.same({"color","name","price"}, tablex.keys(apple(), true))
    end)
  end)
  describe("contains_key", function()
    it("should return true if the key is in the table", function()
      assert.is_true(tablex.contains_key(apple(), 'color'))
      assert.is_true(tablex.contains_key(apple(), 'name'))
      assert.is_true(tablex.contains_key(apple(), 'price'))
      assert.is_true(tablex.contains_key(apple(), 'color', function(x, y)
        return x == y
      end))
    end)
  end)
  describe("tostring", function()
    it("should nicely format a table", function()
      assert.same([[
{-- 0
  ["color"] = "red",
  ["name"] = "apple",
  ["price"] = 200,
}]], tablex.tostring(apple(), true))
    end)
    it("should nicely format a table with sub-tables", function()
      local a = apple()
      assert.same([[
{-- 0
  [1] = {-- 1
    ["color"] = "red",
    ["name"] = "apple",
    ["price"] = 200,
  },
  [2] = @1,
  [3] = {} -- 2,
}]], tablex.tostring({a,a,{}}, true))
    end)
  end)
end)
